[package]
name = "ecosimulation"
version = "0.1.0"
authors = ["Will Farris <wfarris@pdx.edu>",
           "Maggie Haddon <mahadd29@pdx.edu>"]
edition = "2018"

[dependencies]
<<<<<<< HEAD
sdl2 = "*"
=======
sdl2 = "0.33.0"
>>>>>>> b7ff8c165c46f33796b7ccc8fbaec664d0257183
